"""
Train an MLP surrogate model on the scalar summaries generated by
generate_surrogate_data.py.

The surrogate learns to predict 6 scalar outputs from 4 input parameters:
  Inputs  : sigma, c, x0_frac, y0_frac
  Outputs : peak_amplitude, peak_time, final_energy,
            energy_half_time, spread_x, spread_y

After training, the script:
  - Saves the model to results/surrogate_model.pt
  - Saves normalisation stats to results/surrogate_norm.npz
  - Produces diagnostic plots to results/surrogate_*.png
  - Prints a breakdown of per-target R² and relative error

Usage
-----
    python train_surrogate.py

Edit the CONFIG section to tune hyperparameters.
"""

import os
import csv
import json

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------------
# CONFIG
# ---------------------------------------------------------------------------

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(REPO_ROOT, 'src')
RESULTS_DIR   = os.path.join(REPO_ROOT, 'results')
DATA_CSV      = os.path.join(RESULTS_DIR, 'surrogate_data.csv')

# Model
HIDDEN_DIMS   = [64, 128, 128, 64]   # MLP layer widths
ACTIVATION    = nn.SiLU               # SiLU (swish) works well for smooth physics

# Training
EPOCHS        = 2000
BATCH_SIZE    = 32
LR            = 1e-3
WEIGHT_DECAY  = 1e-4
VAL_FRACTION  = 0.2
SEED          = 42

# ---------------------------------------------------------------------------
# Input / output column names
# ---------------------------------------------------------------------------

INPUT_COLS  = ['sigma', 'c', 'x0_frac', 'y0_frac']
OUTPUT_COLS = ['peak_amplitude', 'peak_time', 'final_energy',
               'energy_half_time', 'spread_x', 'spread_y']

# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_data(csv_path: str):
    rows = []
    with open(csv_path, 'r', newline='') as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)

    if not rows:
        raise RuntimeError(f"No data found in {csv_path}. Run generate_surrogate_data.py first.")

    X = np.array([[float(r[c]) for c in INPUT_COLS]  for r in rows], dtype=np.float32)
    Y = np.array([[float(r[c]) for c in OUTPUT_COLS] for r in rows], dtype=np.float32)

    print(f"Loaded {len(rows)} runs from {csv_path}")
    print(f"  Input  shape : {X.shape}   columns: {INPUT_COLS}")
    print(f"  Output shape : {Y.shape}   columns: {OUTPUT_COLS}")
    return X, Y


# ---------------------------------------------------------------------------
# Normalisation (z-score on inputs, z-score on outputs)
# ---------------------------------------------------------------------------

def normalise(X, Y):
    x_mean, x_std = X.mean(0), X.std(0) + 1e-8
    y_mean, y_std = Y.mean(0), Y.std(0) + 1e-8
    X_n = (X - x_mean) / x_std
    Y_n = (Y - y_mean) / y_std
    norm = dict(x_mean=x_mean, x_std=x_std, y_mean=y_mean, y_std=y_std)
    return X_n, Y_n, norm


def denormalise_y(Y_n, norm):
    return Y_n * norm['y_std'] + norm['y_mean']


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

class SurrogateMLP(nn.Module):
    def __init__(self, in_dim: int, out_dim: int, hidden_dims: list, activation):
        super().__init__()
        layers = []
        prev = in_dim
        for h in hidden_dims:
            layers += [nn.Linear(prev, h), activation()]
            prev = h
        layers.append(nn.Linear(prev, out_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------

def train(model, loader_train, loader_val, epochs, lr, weight_decay):
    optimiser = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimiser, T_max=epochs)
    criterion = nn.MSELoss()

    train_losses, val_losses = [], []

    for epoch in range(1, epochs + 1):
        # --- train ---
        model.train()
        epoch_loss = 0.0
        for xb, yb in loader_train:
            optimiser.zero_grad()
            pred = model(xb)
            loss = criterion(pred, yb)
            loss.backward()
            optimiser.step()
            epoch_loss += loss.item() * len(xb)
        train_losses.append(epoch_loss / len(loader_train.dataset))

        # --- validate ---
        model.eval()
        with torch.no_grad():
            val_loss = sum(
                criterion(model(xb), yb).item() * len(xb)
                for xb, yb in loader_val
            ) / len(loader_val.dataset)
        val_losses.append(val_loss)

        scheduler.step()

        if epoch % 200 == 0 or epoch == 1:
            print(f"  epoch {epoch:4d}/{epochs}  train={train_losses[-1]:.5f}  val={val_losses[-1]:.5f}")

    return train_losses, val_losses


# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------

def r2_score(y_true, y_pred):
    ss_res = ((y_true - y_pred)**2).sum(0)
    ss_tot = ((y_true - y_true.mean(0))**2).sum(0)
    return 1 - ss_res / (ss_tot + 1e-12)


def evaluate(model, X_val_t, Y_val_raw, norm):
    model.eval()
    with torch.no_grad():
        Y_pred_n = model(X_val_t).numpy()
    Y_pred = denormalise_y(Y_pred_n, norm)

    r2   = r2_score(Y_val_raw, Y_pred)
    rele = np.abs(Y_val_raw - Y_pred) / (np.abs(Y_val_raw) + 1e-12)

    print("\nPer-target evaluation on validation set:")
    print(f"  {'Target':<20}  {'R²':>8}  {'MedRelErr':>10}")
    print(f"  {'-'*42}")
    for i, col in enumerate(OUTPUT_COLS):
        print(f"  {col:<20}  {r2[i]:>8.4f}  {np.median(rele[:,i]):>10.4f}")

    return Y_pred, r2, rele


# ---------------------------------------------------------------------------
# Plots
# ---------------------------------------------------------------------------

def plot_loss(train_losses, val_losses, out_dir):
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.semilogy(train_losses, label='train')
    ax.semilogy(val_losses,   label='val')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('MSE loss (normalised)')
    ax.set_title('Surrogate training loss')
    ax.legend()
    ax.grid(True, linestyle='--', alpha=0.5)
    fig.tight_layout()
    path = os.path.join(out_dir, 'surrogate_loss.png')
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"Saved {path}")


def plot_parity(Y_true, Y_pred, out_dir):
    """Parity (predicted vs actual) plots for each output."""
    n_targets = len(OUTPUT_COLS)
    ncols = 3
    nrows = (n_targets + ncols - 1) // ncols
    for i, col in enumerate(OUTPUT_COLS):  
        plt.scatter(Y_true[:, i], Y_pred[:, i], alpha=0.6, s=20)
        lo = min(Y_true[:, i].min(), Y_pred[:, i].min())
        hi = max(Y_true[:, i].max(), Y_pred[:, i].max())
        plt.plot([lo, hi], [lo, hi], 'r--', linewidth=1)
        r2 = r2_score(Y_true[:, i:i+1], Y_pred[:, i:i+1])[0]
        plt.title(f'{col}\nR²={r2:.3f}')
        plt.xlabel('Actual')
        plt.ylabel('Predicted')
        plt.grid(True, linestyle='--', alpha=0.4)
        plt.savefig(os.path.join(out_dir, f'surrogate_parity_{col}.png'), dpi=150)
        plt.close()



  

def plot_error_by_param(X_val_raw, Y_true, Y_pred, out_dir):
    """Relative error vs each input parameter — reveals where the surrogate struggles."""
    rel_err_mean = np.abs(Y_true - Y_pred).mean(1) / (np.abs(Y_true).mean(1) + 1e-12)

    fig, axes = plt.subplots(1, len(INPUT_COLS), figsize=(4*len(INPUT_COLS), 4))
    for i, col in enumerate(INPUT_COLS):
        axes[i].scatter(X_val_raw[:, i], rel_err_mean, alpha=0.6, s=20)
        axes[i].set_xlabel(col)
        axes[i].set_ylabel('Mean rel. error')
        axes[i].set_title(f'Error vs {col}')
        axes[i].grid(True, linestyle='--', alpha=0.4)

    fig.suptitle('Where does the surrogate struggle?')
    fig.tight_layout()
    path = os.path.join(out_dir, 'surrogate_error_by_param.png')
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"Saved {path}")


# ---------------------------------------------------------------------------
# Speed comparison
# ---------------------------------------------------------------------------

def speed_comparison(model, X_val_t, loader_val, norm):
    """Compare surrogate inference time vs a rough solver estimate."""
    import time

    # surrogate: time inference on the full val set
    model.eval()
    with torch.no_grad():
        t0 = time.perf_counter()
        for _ in range(100):
            _ = model(X_val_t)
        t1 = time.perf_counter()
    surrogate_per_sample = (t1 - t0) / (100 * len(X_val_t)) * 1000  # ms

    print(f"\nSpeed comparison:")
    print(f"  Surrogate inference : {surrogate_per_sample:.4f} ms/sample")
    print(f"  (Solver timing is in results/benchmark_cpu.csv for comparison)")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    torch.manual_seed(SEED)
    np.random.seed(SEED)
    os.makedirs(RESULTS_DIR, exist_ok=True)

    # --- load ---
    X_raw, Y_raw = load_data(DATA_CSV)
    n = len(X_raw)

    # --- train/val split ---
    idx = np.random.permutation(n)
    n_val = max(1, int(n * VAL_FRACTION))
    val_idx, train_idx = idx[:n_val], idx[n_val:]

    X_train_raw, Y_train_raw = X_raw[train_idx], Y_raw[train_idx]
    X_val_raw,   Y_val_raw   = X_raw[val_idx],   Y_raw[val_idx]

    # --- normalise (fit on train only) ---
    X_n, Y_n, norm = normalise(X_train_raw, Y_train_raw)

    x_mean, x_std = norm['x_mean'], norm['x_std']
    y_mean, y_std = norm['y_mean'], norm['y_std']

    X_val_n = (X_val_raw - x_mean) / x_std

    # --- tensors ---
    X_tr_t  = torch.tensor(X_n,        dtype=torch.float32)
    Y_tr_t  = torch.tensor(Y_n,        dtype=torch.float32)
    X_val_t = torch.tensor(X_val_n,    dtype=torch.float32)

    ds_train = TensorDataset(X_tr_t, Y_tr_t)
    ds_val   = TensorDataset(X_val_t, torch.tensor(
        (Y_val_raw - y_mean) / y_std, dtype=torch.float32))

    loader_train = DataLoader(ds_train, batch_size=BATCH_SIZE, shuffle=True)
    loader_val   = DataLoader(ds_val,   batch_size=BATCH_SIZE, shuffle=False)

    # --- model ---
    model = SurrogateMLP(
        in_dim=len(INPUT_COLS),
        out_dim=len(OUTPUT_COLS),
        hidden_dims=HIDDEN_DIMS,
        activation=ACTIVATION,
    )
    n_params = sum(p.numel() for p in model.parameters())
    print(f"\nModel: {n_params} parameters")
    print(model)

    # --- train ---
    print(f"\nTraining for {EPOCHS} epochs...")
    train_losses, val_losses = train(model, loader_train, loader_val, EPOCHS, LR, WEIGHT_DECAY)

    # --- evaluate ---
    Y_pred, r2, rele = evaluate(model, X_val_t, Y_val_raw, norm)

    # --- speed ---
    speed_comparison(model, X_val_t, loader_val, norm)

    # --- plots ---
    plot_loss(train_losses, val_losses, RESULTS_DIR)
    plot_parity(Y_val_raw, Y_pred, RESULTS_DIR)
    plot_error_by_param(X_val_raw, Y_val_raw, Y_pred, RESULTS_DIR)

    # --- save model + norm ---
    model_path = os.path.join(RESULTS_DIR, 'surrogate_model.pt')
    torch.save({
        'model_state': model.state_dict(),
        'hidden_dims': HIDDEN_DIMS,
        'in_dim':      len(INPUT_COLS),
        'out_dim':     len(OUTPUT_COLS),
        'input_cols':  INPUT_COLS,
        'output_cols': OUTPUT_COLS,
    }, model_path)
    print(f"\nModel saved to {model_path}")

    norm_path = os.path.join(RESULTS_DIR, 'surrogate_norm.npz')
    np.savez(norm_path, **{k: v for k, v in norm.items()})
    print(f"Norm stats saved to {norm_path}")

    print("\nDone.")


if __name__ == '__main__':
    main()